version: '3.7'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
#        volumes:
#            - ./data/postgres/data:/var/lib/postgresql/data
        restart: always
    app:
        build:
            dockerfile: Dockerfile
            context: './flaskr'
        depends_on:
            - postgres
        ports:
            - "5000:5000"
        environment:
            - DEBUG=True
            - REDIS_HOST=multi-docker-redis.dhfy4f.0001.euw2.cache.amazonaws.com
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
            - ENV=prod
        volumes:
            - ./flaskr:/app
    worker:
        build:
            dockerfile: Dockerfile
            context: './flaskr'
        command: python worker.py
        environment:
            - REDIS_HOST=multi-docker-redis.dhfy4f.0001.euw2.cache.amazonaws.com:
        volumes:
            - ./flaskr:/app
    nginx:
        build:
            dockerfile: Dockerfile
            context: './nginx'
        depends_on:
          - app
        restart: always
        ports:
        - "80:80"
#    worker:
#        build:
#            dockerfile: Dockerfile
#            context: './worker'
#        volumes:
#            - ./worker:/app
#        environment:
#            - REDIS_HOST=redis-flaskr


