version: '3.7'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"

        restart: always
    redis-server:
        image: redis:6.0-rc3-buster
        ports:
            - "6379:6379"
    redis-worker:
        image: redis:6.0-rc3-buster
        command: --port 6380
        depends_on:
            - redis-server
        ports:
            - "6380:6380"
        restart: always
    app:
        build:
            dockerfile: Dockerfile.dev
            context: './flaskr'
        depends_on:
            - redis-server
            - redis-worker
            - postgres
            - worker
        ports:
            - "5000:5000"
        environment:
            - DEBUG=True
            - REDIS_SERVER_HOST=redis-server
            - REDIS_SERVER_PORT=6379
            - REDIS_WORKER_HOST=redis-worker
            - REDIS_WORKER_PORT=6380
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
            - ENV=prod
            - CONFIG=config.DevelopmentConfig
        volumes:
            - ./flaskr:/app
    worker:
        build:
            dockerfile: Dockerfile
            context: './flaskr'
        command: python worker.py
        depends_on:
          - redis-server
          - redis-worker
        environment:
            - REDIS_SERVER_HOST=redis-server
            - REDIS_SERVER_PORT=6379
            - REDIS_WORKER_HOST=redis-worker
            - REDIS_WORKER_PORT=6380
        volumes:
            - ./flaskr:/app
    nginx:
        build:
            dockerfile: Dockerfile
            context: './nginx'
        depends_on:
          - app
        restart: always
        ports:
        - "80:80"
#    worker:
#        build:
#            dockerfile: Dockerfile
#            context: './worker'
#        volumes:
#            - ./worker:/app
#        environment:
#            - REDIS_HOST=redis-flaskr


